from __future__ import annotations

TABLE_PLANTS = "plants"
TABLE_JOURNAL_ENTRIES = "journal_entries"
TABLE_WATERING_SCHEDULES = "watering_schedules"
TABLE_LIGHT_MEASUREMENTS = "light_measurements"
TABLE_AI_CONVERSATIONS = "ai_conversations"
TABLE_AI_MESSAGES = "ai_messages"

COL_ID = "id"
COL_USER_ID = "user_id"
COL_PLANT_ID = "plant_id"
COL_NAME = "name"
COL_SPECIES = "species"
COL_LOCATION = "location"
COL_PHOTO_URL = "photo_url"
COL_NOTES = "notes"
COL_CONTENT = "content"
COL_TYPE = "type"
COL_CREATED_AT = "created_at"
COL_UPDATED_AT = "updated_at"
COL_LIGHT_PROFILE = "light_profile"
COL_FREQUENCY_DAYS = "frequency_days"
COL_LAST_WATERED_AT = "last_watered_at"
COL_NEXT_DUE_AT = "next_due_at"
COL_NOTIFY_TIME = "notify_time"
COL_ACTIVE = "active"
COL_DEVICE_LUX = "device_lux"
COL_CALIBRATED_LUX = "calibrated_lux"
COL_CONVERSATION_ID = "conversation_id"
COL_ROLE = "role"
COL_TITLE = "title"
