from __future__ import annotations

TABLE_PLANTS = "plants"
TABLE_LOG = "logbook"
TABLE_WATERING = "watering"
TABLE_WATERING_SCHEDULE = "watering_schedule"
TABLE_LIGHT = "light_readings"
TABLE_FERTILIZATIONS = "fertilizations"
TABLE_REPOTTINGS = "repottings"
TABLE_OBSERVATIONS = "observations"
TABLE_PHOTOS = "photos"

COL_ID = "id"
COL_USER_ID = "user_id"
COL_PLANT_ID = "plant_id"
COL_NICKNAME = "nickname"
COL_SPECIES = "species"
COL_CREATED_AT = "created_at"
COL_DATE = "date"
COL_NOTES = "notes"
COL_ENTRY_TYPE = "entry_type"
COL_NEXT_WATERING = "next_watering"
COL_LAST_WATERED = "last_watered"
COL_LIGHT_LEVEL = "light_level"
COL_FERTILIZER_TYPE = "fertilizer_type"
COL_SOIL_MIX = "soil_mix"
COL_POT_SIZE = "pot_size"
COL_IMAGE_URL = "image_url"
